name: Upload OPS Airflow Artifacts to S3
# on action to branches to trigger this workflow 
on:
  push:
    branches: [develop, main, release]
permissions:
  id-token: write
  contents: read
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2
    - name: Set Environments Variables
      run: |
        if [[ "${{github.ref}}" == "refs/heads/develop" ]]; then
          echo "ROLE_TO_ASSUME=ROLE_TO_ASSUME_DEV_VAR" >> $GITHUB_ENV
        fi
        if [[ "${{github.ref}}" == "refs/heads/main" ]]; then
          echo "ROLE_TO_ASSUME=ROLE_TO_ASSUME_DEV_VAR" >> $GITHUB_ENV
        fi
        if [[ "${{github.ref}}" == "refs/heads/release" ]]; then
          echo "ROLE_TO_ASSUME=ROLE_TO_ASSUME_DEV_VAR" >> $GITHUB_ENV
        fi
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: us-east-1
        role-to-assume: arn:aws:iam::724122322268:role/github-actions-upload-s3
    - name: Deploy to AWS S3
      run: aws s3 sync . s3://github-actions-demo1
