name: Upload OPS Airflow Artifacts to S3
# on action to branches to trigger this workflow 
on:
  push:
    branches: [release]
    tags:
      - 'ODH-v[0-9]+\.[0-9]+\.[0-9]+'
      - 'ODH-v[0-9]+\.[0-9]+\.[0-9]+.[0-9a-zA-Z]*'
permissions:
  id-token: write
  contents: read
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
    - name: Step 1 - Checkout
      uses: actions/checkout@v2
    - name: Step 2 - Set Environments Variables
      run: |
        if [[ ( ${{ github.event.ref }} =~ ^refs/tags/ODH-v[0-9]+\.[0-9]+\.[0-9]+*$ ) || ( ${{ github.event.ref }} =~ ^refs/tags/ODH-v[0-9]+\.[0-9]+\.[0-9]+.[0-9a-zA-Z]* ) ]]; then
          echo "Hello ${{github.event.ref}} - I - Success"
          echo "ROLE_TO_ASSUME=ROLE_TO_ASSUME_PROD_VAR" >> $GITHUB_ENV
          echo "BUCKET_NAME=ops-airflow-artifacts-prod" >> $GITHUB_ENV
        elif [[ "${{github.ref}}" == "refs/heads/master" ]]; then
          echo "Hello ${{github.event.ref}} -     II"
          echo "ROLE_TO_ASSUME=ROLE_TO_ASSUME_PREPROD_VAR" >> $GITHUB_ENV
          echo "BUCKET_NAME=ops-airflow-artifacts-preprod" >> $GITHUB_ENV
        else
          echo "Hello ${{github.event.ref}} -    III"
          echo "ROLE_TO_ASSUME=ROLE_TO_ASSUME_DEV_VAR" >> $GITHUB_ENV
          echo "BUCKET_NAME=ops-airflow-artifacts-dev" >> $GITHUB_ENV
        fi
