name: Upload OPS Airflow Artifacts to S3
# on action to branches to trigger this workflow 
on:
  push:
    branches: [develop, main]
permissions:
  id-token: write
  contents: read
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
    - name: Step 1 - Checkout
      uses: actions/checkout@v2
    - name: Step 2 - Set Environments Variables
      run: |
        if [[ "${{github.ref}}" == "refs/heads/develop" ]]; then
          echo "ROLE_TO_ASSUME=ROLE_TO_ASSUME_DEV_VAR" >> $GITHUB_ENV
        fi
        if [[ "${{github.ref}}" == "refs/heads/main" ]]; then
          echo "ROLE_TO_ASSUME=ROLE_TO_ASSUME_PREPROD_VAR" >> $GITHUB_ENV
        fi
    - name: Step 3 - Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{ secrets[env.AWS_REGION] }}
        role-to-assume: ${{ secrets[env.ROLE_TO_ASSUME] }}
    - name: Step 4 - Deploy to AWS S3
      run: aws s3 sync . s3://github-actions-demo1
